# Generated by Django 6.0.2 on 2026-02-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_location_alter_profile_display_name_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
